# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TestGraphs' do

pod 'Charts', '~> 2.2.3'

end

target 'TestGraphsTests' do

end

target 'TestGraphsUITests' do

end

